algoritmo "calcula-media"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

var
 peca,valor, codigo,quantidade :real

inicio
  escreval("Peças")
  escreval("Digite Código da peça")
  leia(codigo)
  
  escreval("Insira a quantidade de peças")
  leia(quantidade)
  
  escreval("Digite o valor da peça")

//calcula a media

  valor<-(quantidade*valor)
  escreval("Código:",codigo,"valor",valor)
  
fimalgoritmo
